[program:kegalle-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/kegalle/app_core/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=nobody
numprocs=2
redirect_stderr=true
stdout_logfile=/home/kegalle/app_core/storage/logs/worker.log
stopwaitsecs=3600
