<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use Illuminate\Support\Str;

class CategorySubSeeder extends Seeder
{
    public function run(): void
    {
        $tree = [
            'Accessories' => [
                'Computer Accessories' => ['Keyboards','Mouse & Trackpads','Monitors & Screens','Webcams','USB Hubs & Adapters','Laptop Bags & Sleeves','Mouse Pads','Memory Cards'],
                'Fashion & Personal Accessories' => ['Sunglasses','Wallets & Purses','Belts','Scarves & Shawls','Caps & Hats','Umbrellas','Keychains','Hair Accessories'],
                'Electronic Accessories' => ['Chargers & Cables','Power Banks','Screen Protectors','Phone Holders','Earphone & Headphone Accessories','Cable Organisers'],
                'Hobby & Pet Accessories' => ['Craft Supplies','Fishing Accessories','Gardening Tools','Pet Collars & Leads','Pet Toys','Aquarium Accessories'],
                'Home & Kitchen Accessories' => ['Storage Organisers','Kitchen Gadgets','Cleaning Accessories','Bathroom Accessories','Decorative Accessories','Candles & Holders'],
                'Vehicle Accessories' => ['Car Seat Covers','Dashboard Accessories','Car Chargers','Tyre Accessories','Motorcycle Accessories','Car Perfumes'],
                'Travel Accessories' => ['Luggage Tags','Travel Pillows','Travel Adapters','Passport Holders','Packing Cubes','Waterproof Bags'],
                'Watch Accessories' => ['Watch Straps','Watch Cases','Watch Tools','Watch Winders','Watch Display Boxes'],
                'Jewellery Accessories' => ['Jewellery Boxes','Cleaning Kits','Display Stands','Jewellery Tools','Anti-Tarnish Strips'],
                'Office Accessories' => ['Pen Holders','Desk Organisers','Notebook Holders','Monitor Stands','Cable Management','Whiteboards & Notice Boards'],
            ],
            'Agriculture, Farming & Livestock' => [
                'Crops & Seeds' => ['Paddy & Rice Seeds','Vegetable Seeds','Fruit Seedlings','Flower Seeds','Herb Seeds','Spice Seedlings','Fertiliser & Compost'],
                'Livestock & Poultry' => ['Cattle & Buffaloes','Goats & Sheep','Pigs','Chickens & Poultry','Ducks & Geese','Rabbits','Quail'],
                'Farm Equipment & Machinery' => ['Tractors','Power Tillers','Water Pumps','Sprayers','Harvesting Equipment','Ploughs & Harrows','Seeders'],
                'Irrigation & Water' => ['Drip Irrigation','Sprinkler Systems','Water Tanks','Pipes & Fittings','Submersible Pumps','Water Meters'],
                'Animal Feed & Nutrition' => ['Cattle Feed','Poultry Feed','Fish Feed','Goat Feed','Hay & Straw','Feed Supplements','Salt Licks'],
                'Pesticides & Agrochemicals' => ['Herbicides','Fungicides','Insecticides','Bio Pesticides','Foliar Fertilisers','Soil Conditioners'],
                'Aquaculture & Fisheries' => ['Fish Fingerlings','Fish Feed','Nets & Traps','Pond Liners','Aerators','Water Quality Kits','Fishing Boats'],
                'Organic Farming' => ['Organic Seeds','Vermicompost','Bio Fertilisers','Organic Pesticides','Compost Bins','Earthworms'],
                'Agri Land & Rentals' => ['Land for Lease','Paddy Land','Home Garden Plots','Coconut Estates','Tea Land','Rubber Land'],
                'Forestry & Timber' => ['Timber Logs','Firewood','Bamboo','Cinnamon','Coconut Shells','Wood Chips','Charcoal'],
                'Rubber & Plantation' => ['Rubber Sheets','Latex','Rubber Seedlings','Plantation Equipment','Tapping Knives','Smoke Houses'],
                'Honey & Bee Products' => ['Raw Honey','Beeswax','Bee Pollen','Propolis','Queen Bees','Bee Hives','Beekeeping Equipment'],
            ],
            'Beauty & Cosmetics' => [
                'Skin Care' => ['Face Wash & Cleansers','Moisturisers & Creams','Sunscreen','Face Masks','Toners & Serums','Eye Creams','Exfoliators'],
                'Hair Care' => ['Shampoos','Conditioners','Hair Oils','Hair Masks','Hair Colour','Hair Styling Products','Hair Loss Treatments'],
                'Makeup & Cosmetics' => ['Foundation & Concealer','Lipstick & Lip Gloss','Eye Shadow','Mascara','Blush & Bronzer','Makeup Brushes','Nail Polish'],
                'Perfume & Fragrance' => ['Women\'s Perfume','Men\'s Cologne','Unisex Fragrances','Body Mists','Attar & Oud','Deodorants','Room Sprays'],
                'Personal Hygiene' => ['Soaps & Body Wash','Toothbrushes & Toothpaste','Deodorants','Feminine Hygiene','Shaving Products','Dental Floss'],
                'Herbal & Natural Beauty' => ['Ayurvedic Products','Coconut Oil','Aloe Vera Products','Herbal Face Packs','Natural Soaps','Essential Oils'],
                'Beauty Tools & Devices' => ['Hair Dryers','Straighteners & Curlers','Facial Steamers','Epilators','Electric Shavers','Nail Tools','Makeup Mirrors'],
                'Men\'s Grooming' => ['Beard Care','Face Wash for Men','Body Grooming','Hair Styling for Men','Aftershave','Men\'s Skin Care'],
                'Baby & Kids Beauty' => ['Baby Lotion','Baby Shampoo','Baby Powder','Nappy Rash Cream','Kids Toothpaste','Child-Safe Sunscreen'],
            ],
            'Baby, Kids & Toys' => [
                'Baby Clothing' => ['Newborn Clothes','Baby Bodysuits','Baby Sleepwear','Baby Booties','Baby Hats','Baby Bibs','Baby Socks'],
                'Baby Feeding' => ['Baby Bottles','Breastfeeding Products','Baby Food & Formula','High Chairs','Bottle Warmers','Feeding Spoons','Sippy Cups'],
                'Baby Gear' => ['Prams & Strollers','Baby Carriers','Car Seats','Baby Swings','Baby Bouncers','Travel Cots','Baby Monitors'],
                'Baby Furniture' => ['Baby Cots & Cribs','Changing Tables','Baby Wardrobes','Baby Mattresses','Nursing Chairs','Baby Storage'],
                'Toys for Toddlers' => ['Building Blocks','Push & Pull Toys','Activity Centres','Musical Toys','Ride-On Toys','Soft Toys','Shape Sorters'],
                'Educational Toys' => ['Puzzles','STEM Toys','Learning Games','Flash Cards','Abacus','Science Kits','Coding Toys'],
                'Outdoor Toys' => ['Bicycles','Tricycles','Scooters','Slides & Swings','Sandpits','Water Toys','Sports Toys'],
                'Electronic & Interactive Toys' => ['Remote Control Cars','Drones for Kids','Robots','Interactive Books','Electronic Games','Tablets for Kids'],
                'Dolls & Action Figures' => ['Dolls','Doll Houses','Action Figures','Superhero Toys','Die-Cast Cars','Figurines','Puppets'],
                'Baby Health & Safety' => ['Baby Thermometers','Baby Nail Clippers','Baby Safety Gates','Socket Covers','Baby Medicines','Nappies & Wipes'],
            ],
            'Business, Office & Industrial' => [
                'Office Furniture' => ['Office Desks','Office Chairs','Filing Cabinets','Bookshelves','Conference Tables','Reception Furniture','Partition Screens'],
                'Office Supplies' => ['Paper & Stationery','Pens & Markers','Stamps & Ink','Envelopes','File Folders','Binding Equipment','Label Makers'],
                'Industrial Machinery' => ['CNC Machines','Welding Equipment','Compressors','Generators','Lathes & Mills','Cutting Machines','Packaging Machines'],
                'Safety & Security' => ['CCTV Systems','Fire Extinguishers','Safety Helmets','Safety Boots','High Visibility Vests','First Aid Kits','Security Guards'],
                'Printing & Advertising' => ['Printers & Plotters','Printing Paper','Banner Stands','Signboards','Flex Printing','Ink & Toner','Business Cards'],
                'Business for Sale' => ['Shops for Sale','Restaurants for Sale','Salons for Sale','Pharmacies','Supermarkets','Service Stations','Wholesale Businesses'],
                'Food & Beverage Industry' => ['Commercial Ovens','Refrigeration Equipment','Food Processors','Bakery Equipment','Restaurant Equipment','Bar Equipment'],
                'Construction & Building' => ['Construction Machinery','Scaffolding','Concrete Mixers','Levelling Equipment','Construction Materials','Safety Equipment'],
                'Textile & Garment' => ['Sewing Machines','Embroidery Machines','Fabric & Cloth','Garment Equipment','Tailoring Tools','Fashion Accessories Wholesale'],
                'Electronics & Manufacturing' => ['Soldering Equipment','PCB & Components','Test & Measurement','Assembly Equipment','Clean Room Equipment'],
                'Wholesale & Distribution' => ['FMCG Wholesale','Electronics Wholesale','Clothing Wholesale','Food Wholesale','Hardware Wholesale','Pharmaceutical Wholesale'],
            ],
            'Community & Classifieds' => [
                'Lost & Found' => ['Lost Items','Found Items','Lost Pets','Found Pets','Lost Documents','Missing Persons'],
                'Free Items' => ['Free Furniture','Free Clothing','Free Electronics','Free Plants','Free Food','Free Books','Free Miscellaneous'],
                'Announcements' => ['Community Events','Religious Events','Death Notices','Birthday Announcements','Wedding Announcements','Public Notices'],
                'Carpool & Ride Sharing' => ['Daily Commute','Weekend Trips','Airport Transfers','Intercity Travel','School Runs','Office Pool'],
                'Room & Flatmate Wanted' => ['Room Wanted','Flatmate Wanted','Female Flatmate','Male Flatmate','Short Term Stay','Working Professional'],
                'Volunteers & Charity' => ['Volunteer Opportunities','Charity Drives','Blood Donation','Environmental Drives','Community Service','NGO Help'],
                'Exchange & Swap' => ['Furniture Swap','Electronics Swap','Clothing Swap','Books Swap','Vehicle Swap','Collectibles Swap'],
            ],
            'Computers & Printers' => [
                'Laptops' => ['Business Laptops','Gaming Laptops','Budget Laptops','MacBooks','2-in-1 Laptops','Refurbished Laptops','Laptop Parts'],
                'Desktop Computers' => ['Gaming Desktops','Office Desktops','All-in-One PCs','Mini PCs','Custom Built PCs','Workstations','Refurbished Desktops'],
                'Computer Components' => ['Processors (CPU)','Graphics Cards (GPU)','RAM & Memory','Motherboards','Hard Drives & SSDs','Power Supplies','Computer Cases'],
                'Printers & Scanners' => ['Inkjet Printers','Laser Printers','All-in-One Printers','Photo Printers','Large Format Printers','Scanners','Printer Parts'],
                'Networking Equipment' => ['Routers','Wi-Fi Extenders','Network Switches','Modems','Ethernet Cables','Network Servers','Access Points'],
                'Computer Accessories' => ['Keyboards','Mice','Monitors','Webcams','Speakers','Headsets','USB Hubs','External Hard Drives'],
                'Software & Licences' => ['Operating Systems','Office Software','Antivirus','Design Software','Accounting Software','Educational Software'],
                'Data Storage' => ['External HDDs','USB Flash Drives','Memory Cards','NAS Devices','Cloud Storage','Optical Drives','Tape Drives'],
            ],
            'Digital Products' => [
                'Software & Apps' => ['Mobile Apps','Desktop Software','Web Applications','Plugins & Extensions','Scripts','SaaS Tools'],
                'Digital Art & Design' => ['Logos & Branding','Social Media Templates','Flyer & Poster Templates','Website Templates','UI Kits','Illustrations'],
                'Online Courses & E-books' => ['Business Courses','Tech Courses','Creative Courses','Language Courses','E-books','Study Guides','Exam Papers'],
                'Music & Audio' => ['Music Tracks','Sound Effects','Podcast Templates','Jingles','Ringtones','Audio Books','Beats & Instrumentals'],
                'Video & Footage' => ['Stock Videos','Motion Graphics','Video Templates','Intros & Outros','Animated GIFs','Video Effects'],
                'Web Services' => ['Domain Names','Web Hosting','SSL Certificates','Email Hosting','CDN Services','API Keys','VPN Accounts'],
                'Gaming Digital' => ['Game Accounts','In-Game Items','Game Credits','Game Keys','Cheats & Mods','Gaming Guides'],
            ],
            'Education, Books & Stationery' => [
                'School Books & Textbooks' => ['Grade 1-5 Books','Grade 6-9 Books','O/L Books','A/L Books','University Textbooks','Past Papers','Workbooks'],
                'Stationery & Supplies' => ['Pens & Pencils','Notebooks & Diaries','Geometry Sets','Crayons & Colouring','Rulers & Erasers','Art Supplies','File & Folders'],
                'Tuition & Coaching' => ['Maths Tuition','Science Tuition','English Tuition','Sinhala & Tamil Tuition','A/L Tuition','O/L Tuition','Online Tuition'],
                'Online Courses' => ['IT & Coding','Business & Marketing','Design','Languages','Exam Preparation','Personality Development','Professional Certificates'],
                'Professional Books' => ['Medical Books','Law Books','Engineering Books','Accounting Books','Management Books','Self-Help Books','Biographies'],
                'Religious & Spiritual Books' => ['Buddhist Books','Christian Books','Islamic Books','Hindu Books','Meditation Guides','Dhamma Books'],
                'Children\'s Books' => ['Picture Books','Story Books','Activity Books','Comics','Educational Games','Flash Cards','Nursery Rhymes'],
                'Magazines & Newspapers' => ['Local Magazines','International Magazines','Trade Journals','Academic Journals','Newspapers','Newsletters'],
                'Educational Equipment' => ['Microscopes','Scientific Calculators','Globe & Maps','Projectors','Whiteboards','Laboratory Equipment','Robotics Kits'],
            ],
            'Electrical & Lighting' => [
                'Indoor Lighting' => ['LED Bulbs','Ceiling Lights','Chandeliers','Wall Lights','Under Cabinet Lights','Night Lights','Smart Bulbs'],
                'Outdoor Lighting' => ['Garden Lights','Street Lights','Flood Lights','Solar Lights','Motion Sensor Lights','Pathway Lights','Decorative Outdoor Lights'],
                'Electrical Wiring & Cables' => ['PVC Cables','Armoured Cables','Coaxial Cables','Telephone Cables','Extension Cords','Cable Trays','Conduit Pipes'],
                'Switches & Sockets' => ['Light Switches','Power Sockets','USB Sockets','HDMI Sockets','Smart Switches','Industrial Sockets','Dimmer Switches'],
                'Electrical Panels & Boards' => ['Distribution Boards','MCBs & RCCBs','Fuses','Earthing Equipment','Meter Boxes','Control Panels','Surge Protectors'],
                'Generators & UPS' => ['Petrol Generators','Diesel Generators','Inverters & UPS','Solar Inverters','Battery Banks','Automatic Transfer Switches'],
                'Solar Energy' => ['Solar Panels','Solar Water Heaters','Solar Street Lights','Solar Pumps','Solar Batteries','Solar Charge Controllers'],
                'Electrical Tools' => ['Multimeters','Clamp Meters','Wire Strippers','Crimping Tools','Electrical Tape','Cable Testers','Voltage Testers'],
            ],
            'Electronics' => [
                'Televisions' => ['LED TVs','OLED TVs','Smart TVs','4K TVs','Curved TVs','Projectors','TV Accessories'],
                'Audio & Sound' => ['Bluetooth Speakers','Home Theatre Systems','Soundbars','Earphones & Headphones','Microphones','Amplifiers','Subwoofers'],
                'Cameras & Photography' => ['DSLR Cameras','Mirrorless Cameras','Action Cameras','Point & Shoot Cameras','Camera Lenses','Tripods','Photography Accessories'],
                'Smart Devices' => ['Smart Watches','Smart Home Devices','Fitness Trackers','Smart Speakers','VR Headsets','Smart Displays','IoT Devices'],
                'Video Players & Recording' => ['DVD Players','Blu-Ray Players','Media Players','CCTV & Security Cameras','Dashcams','Video Recorders'],
                'Electric Fans & Cooling' => ['Ceiling Fans','Table Fans','Stand Fans','Tower Fans','Exhaust Fans','Air Coolers','Ventilation Fans'],
                'Power Electronics' => ['Voltage Stabilisers','Surge Protectors','UPS Systems','Power Strips','Adapters & Converters','Inverters'],
                'Electronic Components' => ['Resistors & Capacitors','Microcontrollers','Arduino & Raspberry Pi','Sensors','LEDs & Displays','Transistors','PCBs'],
            ],
            'Events, Tickets & Experiences' => [
                'Concerts & Live Music' => ['Pop Concerts','Rock Concerts','Classical Music','Jazz & Blues','DJ Events','Music Festivals','Live Band Shows'],
                'Sports Events' => ['Cricket Matches','Football Games','Rugby','Athletics','Badminton Tournaments','Chess Tournaments','School Sports Meets'],
                'Cultural & Arts Events' => ['Drama & Theatre','Dance Performances','Art Exhibitions','Film Screenings','Literary Events','Cultural Shows'],
                'Religious Events' => ['Perahera & Processions','Church Events','Mosque Events','Kovil Events','Meditation Retreats','Dhamma Discussions'],
                'Food & Drink Events' => ['Food Festivals','Wine & Dine Events','Cooking Competitions','Restaurant Openings','Street Food Events'],
                'Educational Events' => ['Seminars','Workshops','Conferences','Career Fairs','School Exhibitions','Award Ceremonies'],
                'Travel & Tours' => ['Day Trips','Weekend Tours','Group Travel','Adventure Tours','Heritage Tours','Eco Tours'],
            ],
            'Fashion & Lifestyle' => [
                'Men\'s Clothing' => ['Shirts & T-Shirts','Trousers & Jeans','Formal Wear','Ethnic Wear','Shorts','Jackets & Coats','Underwear & Socks'],
                'Women\'s Clothing' => ['Dresses','Sarees & Blouses','Tops & Blouses','Trousers & Jeans','Ethnic Wear','Kurtas & Salwar','Lingerie & Sleepwear'],
                'Kids\' Clothing' => ['Boys\' Clothing','Girls\' Clothing','Baby Clothing','School Uniforms','Sportswear for Kids','Party Wear for Kids'],
                'Footwear' => ['Men\'s Shoes','Women\'s Shoes','Kids\' Shoes','Sandals & Slippers','Sports Shoes','Formal Shoes','Boots'],
                'Bags & Handbags' => ['Women\'s Handbags','Backpacks','Laptop Bags','Travel Bags','School Bags','Clutches & Evening Bags','Men\'s Bags'],
                'Jewellery & Watches' => ['Gold Jewellery','Silver Jewellery','Gemstone Jewellery','Fashion Jewellery','Bridal Sets','Men\'s Watches','Women\'s Watches'],
                'Ethnic & Bridal Wear' => ['Wedding Sarees','Bridal Gowns','Kurtas & Sherwanis','Lehengas','Bridesmaids Dresses','Wedding Accessories'],
                'Sportswear & Activewear' => ['Gym Wear','Running Gear','Yoga Wear','Swimwear','Cycling Gear','Team Sports Uniforms','Outdoor Wear'],
                'Secondhand & Vintage' => ['Vintage Clothing','Branded Secondhand','Designer Secondhand','Preloved Kids Wear','Vintage Jewellery','Retro Accessories'],
            ],
            'Food & Beverages' => [
                'Fresh Produce' => ['Fresh Vegetables','Fresh Fruits','Herbs & Greens','Organic Produce','Exotic Fruits','Root Vegetables','Salad Leaves'],
                'Meat & Seafood' => ['Fresh Chicken','Beef & Pork','Mutton & Goat','Fresh Fish','Prawns & Shrimp','Dried Fish','Crab & Lobster'],
                'Dairy & Eggs' => ['Fresh Milk','Curd & Yoghurt','Cheese','Butter & Ghee','Eggs','Ice Cream','Cream & Evaporated Milk'],
                'Rice & Grains' => ['White Rice','Red Rice','Basmati Rice','Noodles & Pasta','Oats & Cereals','Flour & Semolina','Pulses & Lentils'],
                'Spices & Condiments' => ['Curry Powder','Chilli Powder','Turmeric','Black Pepper','Cinnamon','Cardamom','Sauces & Pickles'],
                'Bakery & Sweets' => ['Bread & Buns','Cakes & Pastries','Cookies & Biscuits','Sri Lankan Sweets','Chocolates','Roti & Hoppers'],
                'Beverages' => ['Tea & Coffee','Fruit Juices','Soft Drinks','Coconut Water','Herbal Drinks','Energy Drinks','Bottled Water'],
                'Snacks & Ready Foods' => ['Chips & Crisps','Popcorn','Nuts & Dried Fruits','Instant Noodles','Packaged Meals','Frozen Foods','Pickles & Achara'],
                'Organic & Health Foods' => ['Organic Rice','Organic Vegetables','Superfoods','Protein Powders','Health Bars','Gluten-Free Foods','Vegan Foods'],
                'Catering & Meal Services' => ['Home Cooked Meals','Lunch Packets','Wedding Catering','Corporate Catering','Meal Delivery','Tiffin Services'],
                'Oils & Fats' => ['Coconut Oil','Vegetable Oil','Palm Oil','Sesame Oil','Olive Oil','Ghee','Margarine'],
            ],
            'Furniture & Home Living' => [
                'Living Room Furniture' => ['Sofas & Couches','Coffee Tables','TV Units','Bookshelves','Recliners','Sofa Beds','Display Cabinets'],
                'Bedroom Furniture' => ['Double Beds','Single Beds','Wardrobes','Dressing Tables','Bedside Tables','Storage Beds','Bunk Beds'],
                'Dining Room Furniture' => ['Dining Tables','Dining Chairs','Sideboards','Bar Stools','Dining Sets','Display Units','China Cabinets'],
                'Office & Study Furniture' => ['Study Desks','Office Chairs','Filing Cabinets','Computer Desks','Bookcases','Study Tables','Office Storage'],
                'Outdoor & Garden Furniture' => ['Garden Chairs','Garden Tables','Hammocks','Sunbeds','Outdoor Sofas','Garden Benches','Swing Chairs'],
                'Kids\' Furniture' => ['Children\'s Beds','Study Tables for Kids','Toy Storage','Kids\' Wardrobes','Bunk Beds','Baby Furniture'],
                'Storage & Shelving' => ['Wardrobes','Cupboards','Storage Boxes','Wall Shelves','Shoe Racks','Kitchen Cabinets','Garage Storage'],
                'Home Décor' => ['Wall Art & Paintings','Mirrors','Photo Frames','Decorative Items','Vases & Pots','Rugs & Carpets','Curtains & Blinds'],
                'Mattresses & Bedding' => ['Spring Mattresses','Foam Mattresses','Pillows','Bed Sheets','Duvets & Blankets','Mattress Toppers','Pillow Cases'],
                'Antiques & Collectibles' => ['Antique Furniture','Antique Clocks','Vintage Items','Collectible Art','Old Coins','Stamps','Rare Books'],
            ],
            'Gaming & Entertainment' => [
                'Video Game Consoles' => ['PlayStation','Xbox','Nintendo Switch','PC Gaming','Handheld Consoles','Retro Consoles','VR Gaming'],
                'Video Games' => ['Action & Adventure','Sports Games','Racing Games','RPG Games','Strategy Games','Horror Games','Family Games'],
                'Gaming Accessories' => ['Gaming Controllers','Gaming Headsets','Gaming Chairs','Gaming Mice','Mechanical Keyboards','Gaming Monitors','Gaming Desks'],
                'Board Games & Puzzles' => ['Strategy Board Games','Family Games','Chess & Draughts','Card Games','Jigsaw Puzzles','Word Games','Party Games'],
                'Toys & Hobby' => ['Scale Models','Model Railways','RC Vehicles','Drones','Lego & Building Sets','Collectible Figures','DIY Kits'],
                'Musical Entertainment' => ['Karaoke Machines','Music Players','DJ Equipment','Home Theatre','Jukeboxes','Record Players'],
            ],
            'Grocery' => [
                'Packaged Foods' => ['Canned Goods','Sauces & Condiments','Jams & Spreads','Instant Foods','Snack Foods','Dried Foods','Baking Ingredients'],
                'Cleaning Products' => ['Detergents','Floor Cleaners','Toilet Cleaners','Dishwashing Liquid','Bleach & Disinfectants','Air Fresheners','Mops & Buckets'],
                'Personal Care' => ['Soaps','Shampoos','Toothpaste','Deodorants','Sanitary Products','Razors & Blades','Skin Care Basics'],
                'Baby Products' => ['Baby Diapers','Baby Food','Baby Wipes','Baby Cream','Baby Bottles','Baby Formula'],
                'Paper Products' => ['Toilet Paper','Kitchen Towels','Facial Tissues','Paper Plates','Garbage Bags','Aluminium Foil','Cling Wrap'],
                'Beverages & Drinks' => ['Tea & Coffee','Soft Drinks','Juices','Milk & Dairy Drinks','Energy Drinks','Bottled Water','Cordials'],
                'Staples & Dry Goods' => ['Sugar & Salt','Flour & Rice','Pasta & Noodles','Cooking Oil','Butter & Margarine','Vinegar','Coconut Milk'],
                'Frozen & Chilled' => ['Frozen Vegetables','Frozen Fish','Frozen Meat','Ice Cream','Chilled Desserts','Frozen Ready Meals'],
                'Health & Organic' => ['Organic Staples','Health Bars','Vitamins & Supplements','Protein Foods','Natural Sweeteners','Gluten-Free Products'],
            ],
            'Health & Wellness' => [
                'Medicines & Pharmacy' => ['Pain Relief','Cold & Flu','Vitamins & Supplements','Digestive Health','Allergy Medicine','First Aid','Diabetes Care'],
                'Medical Equipment' => ['Blood Pressure Monitors','Glucometers','Thermometers','Nebulisers','Wheelchairs','Walking Aids','Hospital Beds'],
                'Fitness Equipment' => ['Treadmills','Dumbbells & Barbells','Yoga Mats','Resistance Bands','Stationary Bikes','Pull-Up Bars','Weight Benches'],
                'Natural & Herbal' => ['Ayurvedic Medicines','Herbal Teas','Natural Supplements','Essential Oils','Homeopathic Remedies','Traditional Remedies'],
                'Mental Wellness' => ['Meditation Tools','Stress Relief Products','Sleep Aids','Therapy Resources','Self-Help Books','Mindfulness Apps'],
                'Vision & Eye Care' => ['Spectacles','Contact Lenses','Eye Drops','Magnifying Glasses','Reading Glasses','Eye Patches','Lens Solutions'],
                'Dental Care' => ['Toothbrushes','Toothpaste','Dental Floss','Mouthwash','Teeth Whitening','Braces Accessories','Denture Care'],
                'Orthopedic & Joint Care' => ['Knee Supports','Back Braces','Ankle Supports','Orthopedic Pillows','Heat Therapy','Compression Socks','Posture Correctors'],
                'Sexual Health' => ['Contraceptives','Pregnancy Tests','Fertility Products','Sexual Wellness Products','Lubricants','Health Monitors'],
            ],
            'Home & Kitchen Appliances' => [
                'Cooking Appliances' => ['Rice Cookers','Pressure Cookers','Slow Cookers','Induction Cooktops','Gas Cookers','Microwave Ovens','Electric Kettles'],
                'Refrigeration' => ['Refrigerators','Deep Freezers','Wine Coolers','Mini Fridges','Ice Makers','Chest Freezers'],
                'Washing & Laundry' => ['Washing Machines','Dryers','Irons & Steamers','Ironing Boards','Clotheslines','Laundry Baskets'],
                'Cleaning Appliances' => ['Vacuum Cleaners','Robot Vacuums','Steam Mops','Wet & Dry Vacuums','Air Purifiers','Dehumidifiers'],
                'Small Kitchen Appliances' => ['Blenders','Mixers & Grinders','Toasters','Sandwich Makers','Food Processors','Juicers','Coffee Machines'],
                'Air Conditioning & Cooling' => ['Air Conditioners','Stand Fans','Ceiling Fans','Air Coolers','Portable ACs','Window ACs','Split ACs'],
                'Water & Home Care' => ['Water Purifiers','Water Heaters','Water Dispensers','Humidifiers','Air Purifiers','Dishwashers'],
            ],
            'Home Improvement, Garden, Tools & DIY' => [
                'Hand Tools' => ['Hammers','Screwdrivers','Wrenches','Pliers','Chisels','Hand Saws','Measuring Tapes','Levels'],
                'Power Tools' => ['Drills','Grinders','Circular Saws','Jigsaws','Sanders','Nail Guns','Heat Guns','Rotary Tools'],
                'Plumbing' => ['Pipes & Fittings','Taps & Valves','Toilets & Cisterns','Sinks & Basins','Shower Sets','Water Tanks','Drainage Products'],
                'Painting & Decorating' => ['Paints & Primers','Paintbrushes & Rollers','Masking Tape','Wallpaper','Putty & Fillers','Stencils','Paint Trays'],
                'Flooring & Tiles' => ['Ceramic Tiles','Vinyl Flooring','Laminate Flooring','Timber Flooring','Granite & Marble','Grout & Adhesive','Carpets'],
                'Doors & Windows' => ['Wooden Doors','Steel Doors','uPVC Windows','Aluminium Windows','Door Handles','Window Locks','Blinds & Shutters'],
                'Roofing & Ceilings' => ['Roofing Sheets','Clay Tiles','Asbestos Free Sheets','Ceiling Boards','Roof Gutters','Waterproofing','Insulation'],
                'Garden & Outdoor' => ['Lawn Mowers','Garden Hoses','Plant Pots','Garden Soil','Seeds & Bulbs','Pruning Tools','Outdoor Furniture'],
                'Electrical DIY' => ['Light Fittings','Switches & Sockets','Wiring Accessories','Junction Boxes','Circuit Breakers','Cable Clips','Conduit'],
                'Building Materials' => ['Cement & Sand','Bricks & Blocks','Timber & Boards','Steel Rods','Roofing Materials','Adhesives','Insulation Boards'],
                'Storage & Workshop' => ['Tool Cabinets','Workbenches','Storage Racks','Pegboards','Tool Bags','Safety Equipment','Workshop Lights'],
                'Cleaning & Maintenance' => ['Pressure Washers','Cleaning Chemicals','Floor Polishers','Drain Unblocking','Rust Removers','Lubricants'],
            ],
            'Jobs & Careers' => [
                'IT & Technology' => ['Software Development','Web Design','Network & Systems','Cybersecurity','Data Science','IT Support','Digital Marketing'],
                'Sales & Marketing' => ['Sales Executives','Marketing Managers','Brand Promoters','Field Sales','Telesales','Business Development','Media & PR'],
                'Finance & Accounting' => ['Accountants','Finance Managers','Auditors','Bookkeepers','Financial Analysts','Bank Jobs','Insurance Jobs'],
                'Healthcare & Medical' => ['Doctors & Physicians','Nurses','Pharmacists','Lab Technicians','Physiotherapists','Dentists','Health Administrators'],
                'Education & Training' => ['School Teachers','Tuition Teachers','Lecturers','Training Officers','Curriculum Developers','School Administrators'],
                'Construction & Engineering' => ['Civil Engineers','Site Supervisors','Masons','Carpenters','Electricians','Plumbers','Quantity Surveyors'],
                'Hospitality & Tourism' => ['Hotel Jobs','Restaurant Jobs','Tourism Officers','Travel Agents','Chefs & Cooks','Housekeeping','Event Management'],
                'Administration & HR' => ['Office Managers','Receptionists','Data Entry','HR Managers','Secretaries','Personal Assistants','Clerks'],
                'Driving & Transport' => ['Truck Drivers','Delivery Riders','Bus Drivers','Tuk-Tuk Drivers','Lorry Drivers','Tanker Drivers','School Van Drivers'],
                'Domestic & Household' => ['House Maids','Baby Sitters','Cooks','Gardeners','Security Guards','Caretakers','Elderly Care'],
                'Factory & Production' => ['Machine Operators','Quality Controllers','Production Supervisors','Garment Workers','Packaging Staff','Assembly Workers'],
            ],
            'Kitchen & Dining' => [
                'Cookware' => ['Pots & Pans','Pressure Cookers','Woks','Kadai & Currypots','Baking Trays','Casserole Dishes','Steamers'],
                'Kitchen Utensils' => ['Spatulas & Ladles','Knives & Cutting Boards','Graters & Peelers','Whisks & Beaters','Colanders','Measuring Cups','Mixing Bowls'],
                'Dinnerware & Tableware' => ['Plates & Bowls','Cups & Mugs','Glasses & Tumblers','Cutlery Sets','Serving Dishes','Jugs & Pitchers','Trays'],
                'Storage & Organisation' => ['Food Storage Containers','Spice Racks','Jar Sets','Bread Bins','Refrigerator Organisers','Kitchen Cabinets','Pantry Organisation'],
                'Water & Beverages' => ['Water Bottles','Thermos Flasks','Water Filters','Tea & Coffee Sets','Juicers','Blenders','Dispensers'],
                'Baking & Desserts' => ['Baking Moulds','Rolling Pins','Cake Decorating','Pastry Tools','Cookie Cutters','Measuring Sets','Baking Mats'],
                'Cleaning & Hygiene' => ['Dish Racks','Scrubbers & Sponges','Dish Soap','Kitchen Towels','Aprons','Gloves','Sink Accessories'],
            ],
            'Mobile Phones & Tablets' => [
                'Smartphones' => ['Samsung','Apple iPhone','Xiaomi','Oppo','Vivo','Huawei','Nokia','Realme'],
                'Feature Phones' => ['Basic Mobile Phones','Button Phones','Dual SIM Phones','Senior Friendly Phones','Rugged Phones'],
                'Tablets' => ['Apple iPads','Samsung Galaxy Tabs','Amazon Kindle','Android Tablets','Kids Tablets','Drawing Tablets'],
                'Phone Accessories' => ['Phone Cases & Covers','Screen Protectors','Chargers & Cables','Power Banks','Pop Sockets','Phone Stands','Selfie Sticks'],
                'SIM Cards & Plans' => ['Prepaid SIMs','Postpaid Plans','Data SIMs','International SIMs','eSIM','Recharge Vouchers'],
                'Refurbished Phones' => ['Refurbished Samsung','Refurbished iPhone','Refurbished Xiaomi','Certified Preloved','Unlocked Phones'],
                'Mobile Repairs & Parts' => ['Phone Screens','Batteries','Charging Ports','Back Covers','Camera Parts','Phone Repair Services'],
            ],
            'Other' => [
                'Miscellaneous' => ['Uncategorised Items','Random & Unique','Weird & Wonderful','Clearance Items','Bundle Deals','Mystery Items'],
                'Seasonal Items' => ['New Year Items','Christmas Decorations','Avurudu Items','Vesak Decorations','Deepavali Items','Ramadan Items'],
                'Charity & Donations' => ['Charity Sales','Donation Requests','Fundraising Items','Support Causes','Volunteer Items'],
                'Barter & Trade' => ['Swap & Exchange','Trade Offers','Barter Deals','Skill Exchange','Time Banking'],
            ],
            'Pets & Animals' => [
                'Dogs' => ['Puppies for Sale','Dog Food','Dog Accessories','Dog Clothing','Dog Training','Dog Grooming','Dog Kennels','Dog Health'],
                'Cats' => ['Kittens for Sale','Cat Food','Cat Accessories','Cat Toys','Cat Litter','Cat Grooming','Cat Carriers','Cat Health'],
                'Birds' => ['Parrots & Parakeets','Love Birds','Canaries','Pigeons','Budgerigars','Bird Cages','Bird Food','Bird Accessories'],
                'Fish & Aquatic' => ['Tropical Fish','Goldfish','Aquariums','Fish Food','Aquarium Plants','Water Treatment','Aquarium Accessories'],
                'Rabbits & Small Animals' => ['Rabbits','Guinea Pigs','Hamsters','Gerbils','Small Animal Cages','Small Animal Food','Small Animal Accessories'],
                'Reptiles' => ['Lizards','Turtles','Snakes','Terrariums','Reptile Food','Heat Lamps','Reptile Accessories'],
                'Pet Services' => ['Veterinary Services','Pet Grooming','Pet Sitting','Dog Walking','Pet Training','Pet Boarding','Pet Transport'],
                'Pet Food & Treats' => ['Dog Food','Cat Food','Bird Seed','Fish Food','Pet Treats','Organic Pet Food','Raw Pet Food'],
            ],
            'Property & Real Estate' => [
                'Houses for Sale' => ['Detached Houses','Semi-Detached Houses','Terraced Houses','Bungalows','Luxury Villas','Colonial Houses','New Build Houses'],
                'Apartments & Flats for Sale' => ['Studio Apartments','1 Bedroom Flats','2 Bedroom Flats','3 Bedroom Flats','Penthouses','Serviced Apartments','Condominiums'],
                'Land for Sale' => ['Residential Land','Commercial Land','Agricultural Land','Paddy Fields','Coconut Estates','Tea Land','Bare Land'],
                'Houses for Rent' => ['Furnished Houses','Unfurnished Houses','Short Term Rent','Long Term Rent','Family Houses','Single Room Rent','Annexes'],
                'Apartments for Rent' => ['Furnished Apartments','Unfurnished Apartments','Short Stay Rooms','Boarding Houses','Monthly Rent','Weekly Rent'],
                'Commercial Property' => ['Shops for Rent','Office Space','Warehouses','Industrial Buildings','Showrooms','Hotels & Guesthouses','Restaurants for Rent'],
                'Holiday & Short Stay' => ['Holiday Homes','Beach Bungalows','Hill Country Retreats','Holiday Apartments','Guesthouses','Villa Rentals'],
                'Property Services' => ['Real Estate Agents','Property Valuers','Legal Services','Mortgage & Finance','Property Management','Architects','Interior Design'],
            ],
            'Services' => [
                'Home Services' => ['Plumbers','Electricians','Carpenters','Painters','Cleaners','Pest Control','Gardeners','AC Repair'],
                'IT & Tech Services' => ['Web Development','App Development','IT Support','CCTV Installation','Networking','Computer Repair','Digital Marketing'],
                'Repair & Maintenance' => ['Mobile Repair','Laptop Repair','TV Repair','Appliance Repair','Vehicle Repair','Furniture Repair','Watch Repair'],
                'Beauty & Wellness Services' => ['Hair Salons','Beauty Parlours','Massage Therapy','Nail Salons','Spa Services','Tattoo Services','Barbershops'],
                'Education & Tutoring' => ['School Tutors','University Tutors','Music Teachers','Dance Teachers','Language Classes','Driving Instructors','Art Classes'],
                'Photography & Video' => ['Wedding Photography','Event Photography','Product Photography','Video Production','Drone Photography','Photo Editing','Videography'],
                'Events & Entertainment' => ['Wedding Planners','Event Decorators','DJs & MCs','Catering Services','Tent & Equipment Hire','Photographers','Florists'],
                'Transport & Delivery' => ['Goods Transport','Van Hire','Movers & Packers','Courier Services','Taxi & Cab','Tuk-Tuk Services','Three Wheeler Hire'],
                'Financial Services' => ['Accounting','Tax Preparation','Legal Services','Insurance Agents','Loan Services','Investment Advice','Bookkeeping'],
                'Construction & Building' => ['Architects','Civil Engineers','Building Contractors','Interior Designers','Quantity Surveyors','Landscapers','Roofing Services'],
                'Health & Medical Services' => ['General Practitioners','Dentists','Physiotherapists','Home Nursing','Lab Testing','Ambulance Services','Medical Equipment Rental'],
            ],
            'Sports & Hobbies' => [
                'Cricket' => ['Cricket Bats','Cricket Balls','Cricket Helmets','Cricket Pads','Cricket Gloves','Cricket Bags','Cricket Clothing'],
                'Football & Soccer' => ['Footballs','Football Boots','Football Jerseys','Shin Guards','Goal Nets','Training Equipment','Football Accessories'],
                'Badminton' => ['Badminton Rackets','Shuttlecocks','Badminton Shoes','Badminton Bags','Badminton Nets','Badminton Clothing','Grip Tapes'],
                'Gym & Fitness' => ['Dumbbells','Barbells & Weight Plates','Treadmills','Exercise Bikes','Yoga Mats','Resistance Bands','Gym Gloves'],
                'Outdoor & Adventure' => ['Tents & Camping','Hiking Boots','Backpacks','Climbing Gear','Water Sports','Cycling','Fishing Gear'],
                'Swimming' => ['Swimming Costumes','Goggles','Swim Caps','Kickboards','Fins & Paddles','Pool Floats','Water Polo Equipment'],
                'Combat Sports' => ['Boxing Gloves','MMA Equipment','Karate Gear','Taekwondo Equipment','Wrestling Gear','Kickboxing Equipment'],
                'Racket Sports' => ['Tennis Rackets','Table Tennis','Squash Rackets','Badminton','Racket Bags','Balls','Court Accessories'],
                'Hobbies & Crafts' => ['Painting & Drawing','Photography','Knitting & Sewing','Model Making','Stamp Collecting','Coin Collecting','Woodworking'],
                'Music & Instruments' => ['Guitars','Keyboards & Pianos','Drums','Violins','Flutes','Ukuleles','Microphones','Music Accessories'],
                'Cycling' => ['Mountain Bikes','Road Bikes','BMX Bikes','Kids Bikes','Electric Bikes','Cycling Helmets','Cycling Accessories'],
            ],
            'Travel, Tourism & Accommodation' => [
                'Hotels & Resorts' => ['Budget Hotels','Mid-Range Hotels','Luxury Hotels','Beach Resorts','Hilltop Hotels','Boutique Hotels','Heritage Hotels'],
                'Guesthouses & B&B' => ['Family Guesthouses','Backpacker Guesthouses','Homestays','Bed & Breakfast','Farm Stays','Eco Lodges'],
                'Tour Packages' => ['Day Tours','Weekend Packages','Cultural Tours','Adventure Tours','Wildlife Tours','Beach Holidays','Honeymoon Packages'],
                'Transport & Transfers' => ['Airport Transfers','Day Hire Cars','Van Hire','Bus Charters','Tuk-Tuk Tours','Motorbike Rentals','Boat Trips'],
                'Travel Accessories' => ['Luggage & Bags','Travel Pillows','Travel Adapters','Travel Insurance','Guidebooks','Maps','Travel Toiletries'],
                'Kegalle District Stays' => ['Kegalle Town','Mawanella','Rambukkana','Warakapola','Ruwanwella','Dehiowita','Aranayake'],
            ],
            'TV, Audio & Home Entertainment' => [
                'Televisions' => ['Smart TVs','4K & 8K TVs','OLED & QLED TVs','LED TVs','Budget TVs','Large Screen TVs','Portable TVs'],
                'Home Theatre' => ['Home Theatre Systems','Soundbars','AV Receivers','Surround Sound Speakers','Subwoofers','Projectors','Projection Screens'],
                'Music Systems' => ['Bluetooth Speakers','Hi-Fi Systems','Mini Hi-Fi','Portable Speakers','Record Players','CD Players','Radios'],
                'Streaming & Media' => ['Streaming Sticks','Set-Top Boxes','Media Players','Android TV Boxes','Gaming Consoles','Smart Home Hubs'],
                'TV Accessories' => ['TV Mounts & Stands','HDMI Cables','Remote Controls','TV Cabinets','Set-Top Box Accessories','Antenna & Satellite'],
                'Headphones & Earphones' => ['Over-Ear Headphones','In-Ear Earphones','True Wireless Earbuds','Gaming Headsets','Noise Cancelling','Sports Earphones'],
            ],
            'Vehicle Parts' => [
                'Engine & Drivetrain' => ['Engine Parts','Gearboxes','Clutches','Driveshafts','Engine Mounts','Timing Belts','Camshafts'],
                'Body Parts & Panels' => ['Bonnets','Doors','Bumpers','Wings & Fenders','Mirrors','Windscreens','Grilles'],
                'Brakes & Suspension' => ['Brake Pads','Brake Discs','Shock Absorbers','Springs','Control Arms','Wheel Bearings','Steering Parts'],
                'Electrical Parts' => ['Alternators','Starters','Car Batteries','Fuse Boxes','Sensors','Wiring Looms','Headlights & Taillights'],
                'Tyres & Wheels' => ['Car Tyres','Motorbike Tyres','Alloy Wheels','Steel Wheels','Spare Tyres','Wheel Nuts','Tyre Valves'],
                'Filters & Fluids' => ['Oil Filters','Air Filters','Fuel Filters','Engine Oil','Coolant','Brake Fluid','Power Steering Fluid'],
                'Interior Parts' => ['Car Seats','Dashboard Parts','Steering Wheels','Carpets & Mats','Door Handles','Centre Consoles','Sunroofs'],
                'Exhaust & Fuel' => ['Exhaust Pipes','Silencers','Catalytic Converters','Fuel Pumps','Carburettors','Fuel Injectors','Fuel Tanks'],
                'Three-Wheeler Parts' => ['Bajaj Parts','TVS Three-Wheeler Parts','Three-Wheeler Engines','Three-Wheeler Body Parts','Three-Wheeler Electrical'],
                'Motorcycle Parts' => ['Motorcycle Engines','Motorcycle Tyres','Motorcycle Brakes','Fuel Tanks','Exhausts','Handlebars','Motorcycle Chains'],
            ],
            'Vehicles & Automotive' => [
                'Cars for Sale' => ['Suzuki Cars','Toyota Cars','Honda Cars','Nissan Cars','Mitsubishi Cars','BMW & Mercedes','Hybrid Cars'],
                'Vans & Lorries' => ['Cargo Vans','Minivans','Lorries & Trucks','Pickups','Tipper Trucks','Refrigerated Vans','Curtain Siders'],
                'Motorcycles & Scooters' => ['Honda Motorcycles','Yamaha Motorcycles','TVS Motorcycles','Bajaj Motorcycles','Scooters','Electric Scooters','Sports Bikes'],
                'Three-Wheelers' => ['Bajaj Three-Wheelers','TVS Three-Wheelers','Electric Three-Wheelers','Auto Rickshaws','Tuk-Tuks for Hire'],
                'Buses & Coaches' => ['Mini Buses','Tourist Coaches','School Buses','Private Hire Buses','CTB Buses','Luxury Coaches'],
                'Agricultural Vehicles' => ['Tractors','Power Tillers','Harvesters','Mini Trucks','Goods Vehicles','Water Bowsers'],
                'Electric Vehicles' => ['Electric Cars','Electric Motorcycles','Electric Three-Wheelers','Electric Bicycles','Electric Scooters','EV Accessories'],
                'Boats & Watercraft' => ['Fishing Boats','Speed Boats','Canoes','Kayaks','Boat Engines','Boat Accessories'],
                'Vehicle Hire & Leasing' => ['Car Hire','Van Hire','Motorbike Hire','Tuk-Tuk Hire','Lorry Hire','Bus Charter','Long-Term Leasing'],
                'Vehicle Services' => ['Car Wash','Car Service Centres','Tyre Fitting','Auto Electrical','Body & Paint Shops','Vehicle Registration','Insurance'],
                'Spare Parts & Accessories' => ['Car Accessories','Motorbike Accessories','Three-Wheeler Accessories','Car Audio','Dashcams','GPS Trackers'],
            ],
        ];

        $order = 1;
        foreach ($tree as $parentName => $subs) {
            $parent = Category::where('name', $parentName)->whereNull('parent_id')->first();
            if (!$parent) {
                $this->command->warn("Parent not found: $parentName");
                continue;
            }

            $subOrder = 1;
            foreach ($subs as $subName => $leaves) {
                $sub = Category::firstOrCreate(
                    ['name' => $subName, 'parent_id' => $parent->id],
                    [
                        'slug'       => Str::slug($subName) . '-' . $parent->id,
                        'is_active'  => 1,
                        'sort_order' => $subOrder++,
                        'type'       => $parent->type ?? 'listing',
                    ]
                );

                $leafOrder = 1;
                foreach ($leaves as $leafName) {
                    Category::firstOrCreate(
                        ['name' => $leafName, 'parent_id' => $sub->id],
                        [
                            'slug'       => Str::slug($leafName) . '-' . $sub->id,
                            'is_active'  => 1,
                            'sort_order' => $leafOrder++,
                            'type'       => $parent->type ?? 'listing',
                        ]
                    );
                }
            }

            $this->command->info("✓ $parentName — " . count($subs) . " subs");
        }

        $total = Category::count();
        $this->command->info("Total categories in DB: $total");
    }
}
